version: '3.8'

services:
  api:
    build: .
    restart: always
    depends_on:
      - database
      - mailserver
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      SMTP_HOST: mailserver
      SMTP_PORT: 25
    networks:
      - app_network

  webserver:
    image: nginx:latest
    restart: always
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - app_network

  database:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    networks:
      - app_network

  mailserver:
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:25"
      - "8025:8025"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
