services:
  api:
    build: .
    restart: always
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
    expose:
      - "3000"
    networks:
      - app_network

  webserver:
    image: nginx:latest
    restart: always
    depends_on:
      - api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - "80"
    ports:
      - "80:80"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge